# Array(数组)

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

数组的数据类型

In [5]:
type(a)

numpy.ndarray

数组的大小 array的shape属性

In [6]:
a.shape

(3,)

结果(3,)是一个一维数组

使用reshape()将其明确指定为行向量或列向量

In [14]:
a = a.reshape((1,-1))

1 表示整个数组只有一行，-1 是一个占位符,表示的其实是3(3个元素)

In [16]:
a.shape

(1, 3)

从数组大小看出是1行3列

假设数组有6个元素

In [17]:
a=np.array([1,2,3,4,5,6])

In [18]:
a.shape

(6,)

In [20]:
a=a.reshape((2, -1))

In [21]:
a.shape

(2, 3)

2行，-1依旧代表3。2行3列

In [22]:
a=a.reshape((-1, 2))

a又变成了3行2列数组

In [24]:
a.shape

(3, 2)

修改数组中的元素

In [25]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a[2, 0]

5

In [27]:
a[2, 0]=55

In [28]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

numpy中创建数组的函数

**zeros**

In [31]:
a=np.zeros((3, 3))

In [32]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**ones**

In [33]:
a=np.ones((2, 3))

In [34]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

**full**

In [35]:
a=np.full((3,3),0)

In [36]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
a=np.full((2,3),1)

In [38]:
a

array([[1, 1, 1],
       [1, 1, 1]])

**eye** 

In [40]:
a=np.eye(3)

In [41]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**random.random**

In [42]:
a=np.random.random((3, 4))

In [43]:
a

array([[0.97726787, 0.1045681 , 0.08823799, 0.43910718],
       [0.85943887, 0.10341152, 0.32688075, 0.03692603],
       [0.38672821, 0.21429194, 0.89028086, 0.88591616]])

# 索引

In [77]:
a=np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]])

In [50]:
a[-2: , 1:3]

array([[ 6,  7],
       [10, 11]])

-2表示倒数第二行；1:3表示第二到第三个元素

In [51]:
a[1, -2]

7

1表示编号为1的行，也就是第二行；-2表示倒数第二个元素

In [58]:
b=a[2,3]

In [59]:
b

12

In [62]:
type(b)

numpy.int32

In [61]:
b.shape

()

索引操作后，维度可能降低

操作每行的某个元素：

In [75]:
a[np.arange(3), 1]+=10

In [82]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

arange()函数

In [66]:
np.arange(3)

array([0, 1, 2])

In [67]:
np.arange(3,7)

array([3, 4, 5, 6])

或者

In [83]:
a[np.arange(3), [1,1,1]] += 10

In [84]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

或者

In [85]:
a[[0,1,2],[1,1,1]] += 10

In [86]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

获取大于10的数

In [87]:
result_index=a>10

In [88]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [89]:
a[result_index]

array([32, 36, 40, 11, 12])

可以简化操作为

In [90]:
a[a>10]

array([32, 36, 40, 11, 12])

# 元素的数据类型

In [91]:
a = np.array([1,2])

In [92]:
a.dtype

dtype('int32')

In [93]:
a=np.array([1.1,2.2])

In [96]:
a.dtype

dtype('float64')

In [98]:
a=np.array([1,1.1])

In [99]:
a.dtype

dtype('float64')

In [100]:
a=np.array([1.1,2.2],dtype=np.int64)

In [101]:
a

array([1, 2], dtype=int64)

In [102]:
a=np.array([1.2,2.1])

In [104]:
b=np.array(a,dtype=np.int64)

In [105]:
b

array([1, 2], dtype=int64)

# 数学运算与常用函数

In [107]:
a=np.array([[1,2],
          [3,4]])

In [108]:
b=np.array([[5,6],
           [7,8]])

In [109]:
a+b

array([[ 6,  8],
       [10, 12]])

In [110]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [111]:
a-b

array([[-4, -4],
       [-4, -4]])

In [112]:
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [113]:
a*b

array([[ 5, 12],
       [21, 32]])

In [114]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [115]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [116]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [117]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

矩阵乘法(左列数 == 右行数)

In [118]:
a

array([[1, 2],
       [3, 4]])

In [119]:
b=np.array([[1,2,3],
          [4,5,6]])

In [120]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [121]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

**sum**

In [122]:
a

array([[1, 2],
       [3, 4]])

In [123]:
np.sum(a)

10

axis=0时，对列进行操作；axis=1时，对行进行操作 (axis，纵轴)

In [124]:
np.sum(a,axis=0)

array([4, 6])

In [126]:
np.sum(a,axis=1)

array([3, 7])

**mean**

In [128]:
a

array([[1, 2],
       [3, 4]])

In [129]:
np.mean(a)

2.5

In [130]:
np.mean(a,axis=0)

array([2., 3.])

In [131]:
np.mean(a,axis=1)

array([1.5, 3.5])

**uniform**

In [132]:
np.random.uniform(3,4)

3.0812332478114355

In [133]:
np.random.uniform(1,100)

75.43603982565192

**tile**

In [134]:
a

array([[1, 2],
       [3, 4]])

In [136]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [137]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [138]:
np.tile(a,(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

**argsort**

In [139]:
a=np.array([[3,2,7,4],
           [10,5,1,8]])

In [140]:
a.argsort()

array([[1, 0, 3, 2],
       [2, 1, 3, 0]], dtype=int64)

In [141]:
a.argsort(axis=0)

array([[0, 0, 1, 0],
       [1, 1, 0, 1]], dtype=int64)

**矩阵的转置**

In [142]:
a

array([[ 3,  2,  7,  4],
       [10,  5,  1,  8]])

In [143]:
a.T

array([[ 3, 10],
       [ 2,  5],
       [ 7,  1],
       [ 4,  8]])

In [144]:
np.transpose(a)

array([[ 3, 10],
       [ 2,  5],
       [ 7,  1],
       [ 4,  8]])

# 广播

In [146]:
a=np.array([[1,2,3],
           [2,3,4],
           [3,4,5],
           [5,6,7]])

In [147]:
b=np.array([1,2,3])

实现a的每行和b相加：

In [148]:
for i in range(4):
    a[i, :]+= b

In [149]:
a

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [ 4,  6,  8],
       [ 6,  8, 10]])

更加高效的方式：

In [150]:
a+np.tile(b,(4,1))

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [ 5,  8, 11],
       [ 7, 10, 13]])

使用广播特性进行操作(不同维度自动转为相同维度后相加)：

In [152]:
a+b

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [ 5,  8, 11],
       [ 7, 10, 13]])